### ISSUE TITLE
Adding BITS logo to the landing page

### ISSUE THREAD

**Issue by divyekalra1** [arc-bphc/arc-bphc.github.io#11]
Our institute needs to be shown some amount of gratitude for the work we've been able to do until now. Adding their logo and a hyperlink that redirects to the main bits website on the landing page is a good start. Refer to #9 for more details.

**Comment by TextZip** [comment]
![image](https://user-images.githubusercontent.com/49020643/125181406-fc529200-e221-11eb-9422-d39608d0eb32.png)
also update the hyperlink for the resources page from https://arc-bphc.github.io/site/resources.html to https://arc-bphc.github.io/site/resources/
